# Generated by Django 5.0.6 on 2024-05-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("done", 1), ("not done", 0)], max_length=100, null=True
            ),
        ),
    ]
