# Generated by Django 5.0.6 on 2024-05-23 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_remove_todo_status_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
    ]
